### ISSUE TITLE
Doesn't work with react-css-modules

### ISSUE THREAD

**Issue by QuietOmen** [ausi/cq-prolyfill#28]
I believe this is more an issue with react-css-modules clobbering the class name in the css file, but I thought I'd place it here so some collaboration could take place and maybe a better solution could be found.

https://github.com/gajus/react-css-modules/issues/168

**Comment by sunny-g** [comment]
@QuietOmen Were you able to get css-modules and cq-prolyfill to play together? I'm having a similar issue using it with React and css-modules.

**Comment by sunny-g** [comment]
Here's how I got it to work (though, only tested with my particular use case and dev environment):

env: 
Node v6.4.0
NPM v3.10.3
Webpack v.1.13.3
PostCSS v.5.2.5
React v15.4.0
CSS-Loader v0.24.0

1. add the postcss plugin to your webpack config:
```js
postcss: function() {
  return [
    require('stylelint'),
    require('cq-prolyfill/postcss-plugin')({}),
    // ... rest of your postcss plugins here
  ];
}
```

Note: I'm also using the `ExtractTextPlugin` which may or may not make a difference when telling `cq` to only `reevaluate` (rather than `reparse`).

2. write a higher-order component to wrap all components that require the use of container queries (have only tested in limited cases, but it seems to work):
```jsx
import { lifecycle } from 'recompose';
const cq = require('cq-prolyfill')({ postcss: true });

const cqWrap = lifecycle({
  componentDidMount() {
    setTimeout(reevaluate);
  }
});

export default cqWrap;

function reevaluate() {
  cq.reevaluate(false);
}
```

3. write your CSS with the appropriate container query:
```css
.container {
  &:global(:container(width < 400px)) {
    display: none; /* for testing */
  }
}
```

Note: this means that *every* component you write will need to be eventually wrapped with this HOC function before being used: 

```js
// using recompose (https://github.com/acdlite/recompose)
export default compose(
  cqWrap,
  toClass
)(Component)
```

**Comment by QuietOmen** [comment]
@sunny-g thanks for the heads up, and sorry I didn't see your comments sooner, the last couple of months have been hectic for me. I think the higher order component is the best we can expect for at the moment...of course I'm hopeful that I might be able to find another solution with the release of webpack 2  (fingers crossed). But this isn't a bad solution, and I actually enjoy using higher order components so I'm okay with the answer. Not sure if we should close this as a temporary solution?

**Comment by sunny-g** [comment]
@QuietOmen fine by me!

I should note the one thing I've found problematic in practice is that with production builds, `cq` ends up requesting my CSS multiple times - aside from the network cost, it doesn't seem to be messing anything up, but just thought I should mention it.

**Comment by ausi** [comment]
@sunny-g You can take a look at issue #24 for how to get rid of the double downloads of CSS files.
